//loaders
export const ENABLE_LOADER = "ENABLE_LOADER";
export const DISABLE_LOADER = "DISABLE_LOADER";

// login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOG_OUT = "LOG_OUT";
export const OTP_VERIFIED = "OTP_VERIFIED";
export const UPDATE_SIGN_UP_LAST_SCREEN_STATUS =
  "UPDATE_SIGN_UP_LAST_SCREEN_STATUS";

export const REJECT_USER_REQUEST="REJECT_USER_REQUEST";
export const REJECT_USER_RESPONSE="REJECT_USER_RESPONSE";
export const REJECT_USER_FAILED="REJECT_USER_FAILED";

export const QR_CODE_REQUEST="QR_CODE_REQUEST";
export const QR_CODE_RESPONSE="QR_CODE_RESPONSE";
export const QR_CODE_FAILED="QR_CODE_FAILED";

export const HIRE_REQUEST = "HIRE_REQUEST";
export const HIRE_RESPONSE = "HIRE_RESPONSE";
export const HIRE_FAILED = "HIRE_FAILED";

export const APPLIED_PROFILE_REQUEST = "APPLIED_PROFILE_REQUEST";
export const APPLIED_PROFILE_RESPONSE = "APPLIED_PROFILE_RESPONSE";
export const APPLIED_PROFILE_FAILED = "APPLIED_PROFILE_FAILED";

export const JOB_DETAILS_REQUEST = "JOB_DETAILS_REQUEST";
export const JOB_DETAILS_RESPONSE = "JOB_DETAILS_RESPONSE";
export const JOB_DETAILS_FAILED = "JOB_DETAILS_FAILED";

export const APPLIED_USER_BY_JOB = "APPLIED_USER_BY_JOB";
export const APPLIED_USER_BY_JOB_RESPONSE = "APPLIED_USER_BY_JOB_RESPONSE";
export const APPLIED_USER_BY_JOB_FAIL = "APPLIED_USER_BY_JOB_FAIL";

export const SAVE_JOB_REQUEST = "SAVE_JOB_REQUEST";
export const SAVE_JOB_RESPONSE = "SAVE_JOB_RESPONSE";
export const SAVE_JOB_FAILED = "SAVE_JOB_FAILED";
export const ADD_JOB_FROM_HOME = 'ADD_JOB_FROM_HOME';

export const SET_TOKEN = "SET_TOKEN";
export const GET_TOKEN = "GET_TOKEN";

export const SET_HOME_PAGE='SET_HOME_PAGE';

export const CREATED_JOB_REQUEST = "CREATED_JOB_REQUEST";
export const CREATED_JOB_RESPONSE = "CREATED_JOB_RESPONSE";
export const CREATED_JOB_FAILED = "CREATED_JOB_FAILED";

export const GET_JOB_TYPES = "GET_JOB_TYPES";
export const FAILURE_JOB_TYPES = "FAILURE_JOB_TYPES";

export const SAVE_POST_DATAS = "SAVE_POST_DATAS";
export const SAVE_AGE = "SAVE_AGE";
export const SAVE_SALARY = "SAVE_SALARY";
export const SAVE_EXPERIENCE = "SAVE_EXPERIENCE";
export const SAVE_QUALIFICATION = "SAVE_QUALIFICATION";
export const SAVE_WORKING_DAYS = "SAVE_WORKING_DAYS";

export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

export const OTP_REQUEST = "OTP_REQUEST";
export const OTP_RESPONSE = "OTP_RESPONSE";
export const OTP_FAILED = "OTP_FAILED";

export const CREATE_PROFILE_REQUEST = "CREATE_PROFILE_REQUEST";
export const CREATE_PROFILE_FAILED = "CREATE_PROFILE_FAILED";
export const CREATE_PROFILE_RESPONSE = "CREATE_PROFILE_RESPONSE";
